using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using TinyDialogsNet;

namespace ASE;

/// <summary>
/// Dumps the disassembly to a plain-text, tab-separated file that a 68k assembler can
/// re-assemble. Opened as a modal dialog from the Debug window, so the emulator is already
/// parked (see <see cref="DebugWindow"/>) and CPU/memory can be sampled directly here.
///
/// Each code line is emitted as   [empty label] TAB mnemonic TAB operands TAB ; $addr: bytes
/// so the assembler sees a leading-whitespace source line (no label), the operation and its
/// operands as separate fields, and the original address/opcode words as a trailing comment.
/// </summary>
public partial class SaveListingWindow : Window
{
    // Maximum number of instructions emitted in segment mode (safety net against a huge range)
    const int MaxSegmentInstructions = 200000;

    public SaveListingWindow()
    {
        InitializeComponent();

        if (!Design.IsDesignMode)
        {
            // The usual case is dumping around where execution stopped, so "From" is
            // pre-filled with the current PC and "To" with a small stretch ahead.
            uint pc = CPU._moira.PC;
            txtFrom.Text = $"{pc:X8}";
            txtTo.Text = $"{pc + 0x100:X8}";
        }
    }

    public void OnCancelClick(object sender, RoutedEventArgs e) => Close();

    public void OnSaveClick(object sender, RoutedEventArgs e)
    {
        string text;
        try
        {
            text = BuildListing();
        }
        catch (Exception ex)
        {
            ShowError($"Could not build the listing: {ex.Message}");
            return;
        }

        // Invalid input: BuildListing has already notified the user
        if (text == null)
            return;

        var (canceled, path) = TinyDialogs.SaveFileDialog("Save assembler listing",
            "listing.asm",
            new FileFilter("68k assembler source", ["*.asm", "*.s", "*.i", "*.txt"]));

        if (canceled || string.IsNullOrWhiteSpace(path))
            return;

        try
        {
            File.WriteAllText(path, text);
        }
        catch (Exception ex)
        {
            ShowError($"Could not save the listing: {ex.Message}");
            return;
        }

        Close();
    }

    /// <summary>
    /// Generates the full listing text according to the window options.
    /// Returns <c>null</c> if the input is invalid (the user has already been notified).
    /// </summary>
    string BuildListing()
    {
        var sb = new StringBuilder();

        sb.Append("; 68000 disassembly listing generated by ASE").Append(Environment.NewLine);
        sb.Append(';').Append(Environment.NewLine);

        if (tglRegisters.IsChecked == true)
            AppendRegisters(sb);

        if (rbWrapPc.IsChecked == true)
        {
            if (!TryParseCount(txtWrapPc.Text, out int count) || count <= 0)
            {
                ShowError("The \"Wrap PC\" value must be a positive number of instructions.");
                return null;
            }

            // Half of the instructions go before the PC to leave it centered in the listing
            int before = count / 2;
            uint addr = FindStartBefore(CPU._moira.PC, before);

            for (int i = 0; i < count; i++)
                addr += (uint)AppendCodeLine(sb, addr);
        }
        else
        {
            if (!TryParseHex(txtFrom.Text, out uint from) || !TryParseHex(txtTo.Text, out uint to))
            {
                ShowError("\"From\" and \"To\" must be hexadecimal addresses.");
                return null;
            }

            // 68000 instructions are word-aligned
            from &= ~1u;
            to &= ~1u;
            if (to < from)
                (from, to) = (to, from);

            uint addr = from;
            for (int i = 0; i < MaxSegmentInstructions && addr <= to; i++)
            {
                addr += (uint)AppendCodeLine(sb, addr);
                if (addr <= from)   // address counter overflow
                    break;
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Disassembles the instruction at <paramref name="addr"/> and appends it as a
    /// re-assemblable tab-separated line. Returns the instruction size in bytes.
    /// </summary>
    int AppendCodeLine(StringBuilder sb, uint addr)
    {
        var (dis, size) = CPU._moira.Disassemble(addr, 250);
        if (size <= 0)
            size = 2;

        // Original opcode words (for the comment that preserves the disassembler info)
        var hex = new StringBuilder();
        for (uint x = 0; x < size; x += 2)
        {
            if (x > 0)
                hex.Append(' ');
            hex.Append($"{ASEMain._mem.Read16(addr + x):X4}");
        }

        // Moira pads the mnemonic up to column 8 with spaces, so the first run of spaces
        // separates the mnemonic from the operands (in MOIRA syntax the operands contain
        // no spaces).
        string dl = dis.TrimEnd();
        int sp = dl.IndexOf(' ');
        string mnem = sp < 0 ? dl : dl.Substring(0, sp);
        string ops = sp < 0 ? "" : dl.Substring(sp + 1).TrimStart();

        sb.Append("\t\t").Append(mnem).Append('\t').Append(ops)
          .Append("\t; $").Append(addr.ToString("X8")).Append(": ").Append(hex)
          .Append(Environment.NewLine);

        return size;
    }

    /// <summary>Dumps all registers as tab-separated comment lines at the beginning of the file.</summary>
    void AppendRegisters(StringBuilder sb)
    {
        var m = CPU._moira;

        sb.Append("; ------------------------------------------------------------").Append(Environment.NewLine);
        sb.Append("; Register dump").Append(Environment.NewLine);
        sb.Append("; ------------------------------------------------------------").Append(Environment.NewLine);

        for (int i = 0; i < 8; i++)
            sb.Append($";\tD{i}\t${m.D[i]:X8}").Append(Environment.NewLine);
        for (int i = 0; i < 7; i++)
            sb.Append($";\tA{i}\t${m.A[i]:X8}").Append(Environment.NewLine);

        sb.Append($";\tSP\t${m.SP:X8}").Append(Environment.NewLine);   // A7
        sb.Append($";\tPC\t${m.PC:X8}").Append(Environment.NewLine);
        sb.Append($";\tSR\t${m.SR:X4}").Append(Environment.NewLine);
        sb.Append("; ------------------------------------------------------------").Append(Environment.NewLine);
        sb.Append(';').Append(Environment.NewLine);
    }

    /// <summary>
    /// Locates the start address from which a forward disassembly produces
    /// <paramref name="wanted"/> instructions before <paramref name="anchor"/>, leaving the
    /// anchor (the PC) centered. Since 68000 instructions have variable length, it looks for
    /// the farthest aligned start that "fits" with the anchor (same as the debug window's
    /// disassembler) and counts backwards from there. If there is not enough valid code
    /// behind, it returns the farthest start found (best effort).
    /// </summary>
    uint FindStartBefore(uint anchor, int wanted)
    {
        anchor &= ~1u;
        if (wanted <= 0 || anchor == 0)
            return anchor;

        // 68000 instructions take at most ~10 bytes; plenty of slack is left.
        uint windowBytes = (uint)wanted * 10u;
        uint windowStart = anchor > windowBytes ? anchor - windowBytes : 0;
        int slots = (int)((anchor - windowStart) / 2);
        if (slots <= 0)
            return anchor;

        // Size (in words) of the instruction starting at each even address of the window
        var sizeInWords = new int[slots];
        for (int i = 0; i < slots; i++)
        {
            var (_, size) = CPU._moira.Disassemble(windowStart + (uint)i * 2, 250);
            sizeInWords[i] = size > 0 ? size / 2 : 1;
        }

        // reachable[i] == true if disassembling from windowStart + i*2 lands exactly on the anchor
        var reachable = new bool[slots + 1];
        reachable[slots] = true;
        for (int i = slots - 1; i >= 0; i--)
        {
            int next = i + sizeInWords[i];
            reachable[i] = next <= slots && reachable[next];
        }

        int startSlot = -1;
        for (int i = 0; i < slots; i++)
            if (reachable[i]) { startSlot = i; break; }

        if (startSlot < 0)
            return anchor;

        // Start addresses of each instruction from the synchronized point up to the anchor;
        // pick the one exactly `wanted` instructions behind (or the farthest one).
        var addrs = new List<uint>();
        uint a = windowStart + (uint)startSlot * 2;
        while (a < anchor)
        {
            addrs.Add(a);
            var (_, size) = CPU._moira.Disassemble(a, 250);
            a += (uint)(size > 0 ? size : 2);
        }

        if (addrs.Count == 0)
            return anchor;
        if (addrs.Count <= wanted)
            return addrs[0];
        return addrs[addrs.Count - wanted];
    }

    static bool TryParseHex(string s, out uint value)
        => uint.TryParse((s ?? "").Trim().TrimStart('$'), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out value);

    static bool TryParseCount(string s, out int value)
        => int.TryParse((s ?? "").Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out value);

    static void ShowError(string message)
        => TinyDialogs.MessageBox("Save listing", message,
            MessageBoxDialogType.Ok, MessageBoxIconType.Error, MessageBoxButton.Ok);
}
